name: Repository Dispatch
on:
  repository_dispatch:
    types: [ app-release ]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      # Dispatch from a workflow.
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        if: ${{ false }}
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: sureshg/openjdk-playground
          event-type: app-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}